version: '3.8'

services:
  tgbot:
    build: .
    container_name: openweatherbot
    environment:
      - ENV=production  # Example environment variable
#    ports:
#      - "8000:8000"  # Map host port 8000 to container port 8000
    volumes:
      - .:/app  # Mount the project directory to the /app directory in the container
    restart: unless-stopped
